Resources:
  StoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: StoreBucket        
      PolicyDocument:
        Statement: 
          - 
            Effect: "Deny"
            Action: 
              - "s3:*"
            Principal: "*"
            Resource:
              - 'arn:aws:s3:::${self:custom.STORE_BUCKET}'
              - 'arn:aws:s3:::${self:custom.STORE_BUCKET}/*'
            Condition:
              StringNotLike:
                aws:userId:
                - '#{StoreBucketRole.RoleId}:*'
                # Role Okta-AWS-PowerUsers https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_federated-home-directory-console.html
                - AROA4HBAQJX2SOHBNW5FE:*
                # SLS user
                - AIDA4HBAQJX24VANULSVM

  S3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ${self:service}-${self:provider.stage}-s3-access-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: AllowAccessToStoreBucket
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - 'arn:aws:s3:::${self:custom.STORE_BUCKET}'

  # https://www.serverless.com/framework/docs/providers/aws/guide/iam/
  SLSDefaultPermissionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ${self:service}-${self:provider.stage}-sls-default-permissions-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:logs'
                  - Ref: 'AWS::Region'
                  - Ref: 'AWS::AccountId'
                  - 'log-group:/aws/lambda/*:*:*'                        
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - "Ref" : "ServerlessDeploymentBucket"